### ISSUE TITLE
Claiming the debug runtime doesn't work on post-singleplayer releases is incorrect, please update it or rename this repo to something unofficial

### ISSUE THREAD

**Issue by lax1dude** [eaglerarchive/eaglercraft-1.5.2-desktopruntime#1]
The latest source is here: [https://gitlab.com/C0ldDev/eaglercraft/-/tree/main/](https://gitlab.com/C0ldDev/eaglercraft/-/tree/main/)

I have made it clear several times that I do not want people to use the desktop runtime as a regular client to play on servers, if you are not gonna respect my wishes and distribute this to entire communities anyway the least you can do is actually provide the latest version.

**Comment by ShoelessTom** [comment]
ok
